### ISSUE TITLE
Small window mode

### ISSUE THREAD

**Issue by sfk26** [Zimzozaur/focus-tui#8]
![IMG_1112](https://github.com/user-attachments/assets/2e7cc05e-9667-4e14-b71b-b00b5f61ffc0)
![IMG_1113](https://github.com/user-attachments/assets/a2a274b3-d6de-403d-82a9-a0112213257a)
It would be nice if the app could work in the background like a small window and look good. Personally, I prefer to see the time while studying or working. So I think it may be useful for other users.

**Comment by matmaer** [comment]
it's ok if you can zoom inside your terminal window

**Comment by Zimzozaur** [comment]
@matmaer what do you mean? To zoom out to make it smaller?

**Comment by matmaer** [comment]
indeed
